# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Sabor
site_author:  ScissorSeven
site_description: >-
  Sabor is where the future works

# Copyright
copyright: Copyright &copy; 2021 - 2022 ScissorSeven

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo192.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  #- redirects:
  #    redirect_maps:
  #      changelog/insiders.md: insiders/changelog.md
  #      conventions.md: philosophy.md
  #      reference/meta-tags.md: reference/index.md
  #      reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
  #      sponsorship.md: insiders/index.md
  #      upgrading.md: upgrade.md
  - minify:
      minify_html: true

# Customization
#extra:
  #analytics:
  #  provider: google
  #  property: !ENV GOOGLE_ANALYTICS_KEY
  #social:
    # - icon: fontawesome/brands/github
    #   link: https://github.com/squidfunk
    # - icon: fontawesome/brands/gitter
    #   link: https://gitter.im/squidfunk/mkdocs-material
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/mkdocs-material/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 项目介绍:
    - 概述: 概述.md
    - 视频: 视频.md
  - 开发设计文档:
    - develop/index.md
    - 需求分析:
      - 需求分析: develop/require/require.md
      - 用户故事: develop/require/user_stories.md
    - 模块与接口设计:
      #- develop/design/index.md
      - 模块设计: develop/design/module.md
      - 接口设计:
        - develop/design/interface/index.md
        - 用户模块: develop/design/interface/users.md
        - 项目模块:
          - develop/design/interface/project/index.md
          - 需求管理: develop/design/interface/project/requirement.md
          - 系统服务管理: develop/design/interface/project/system.md
          - 迭代管理: develop/design/interface/project/iteration.md
        - Git 仓库模块: develop/design/interface/git.md
    - 数据库设计: 
      - 概述: develop/database/overview.md
      - 用户管理系统: develop/database/user.md
      - 项目管理系统: develop/database/project.md
      - 仓库管理系统: develop/database/git.md
  - 用户文档: 
    - 总述: users/总述.md
    - 平台说明: users/平台说明.md
    - 项目管理员: users/项目管理员.md
    - 系统工程师: users/系统工程师.md
    - 开发工程师: users/开发工程师.md
    - 质量保证工程师: users/质量保证工程师.md
    - 分工与致谢: users/分工与致谢.md
  # - 开发记录:
  #   - 前端: 
  #     - Home: insiders/front-end-Home.md
  #     - BUG汇总表: insiders/front-end-BUG汇总表.md
  #     - OTH汇总表: insiders/front-end-OTH汇总表.md
  #     - 开发规范: insiders/front-end-开发规范.md
  #     - 整体需求进度表: insiders/front-end-整体需求进度表.md
  #     - 组会进度汇报: insiders/front-end-组会进度汇报.md
  #     - 过程管理细则: insiders/front-end-过程管理细则.md
  #     - 通信协议: insiders/front-end-通信协议.md
  #     - 项目信息: insiders/front-end-项目信息.md
  #   - 后端: 
  #     - Home: insiders/back-end-Home.md
  #     - 周二测试记录: insiders/back-end-周二测试记录.md
  #     - 数据库: insiders/back-end-数据库.md
  #     - 测试流程: insiders/back-end-测试流程.md
  #     - 通信协议: insiders/back-end-通信协议.md
  #     - 需求列表: insiders/back-end-需求列表.md
  #     - 项目信息: insiders/back-end-项目信息.md
